name: React CI/CD

on:
  push:
    branches: [deploy]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm test
      - run: npm run build
      - run: mv /home/dimaboss/hello-react/hello-react/github-actions-react/github-actions-react/build /home/dimaboss/hello-react/hello-react/github-actions-react/github-actions-react/helloreact
      - run: echo "deploy is ready"
